export const SCREENS = {
  MAIN_MENU: 'MAIN_MENU',
  NOW_PLAYING: 'NOW_PLAYING',
  STATION_LIST: 'STATION_LIST',
  CATEGORY_LIST: 'CATEGORY_LIST',
  STATION_RESULTS: 'STATION_RESULTS',
  SEARCH: 'SEARCH',
  SETTINGS: 'SETTINGS',
  BRIGHTNESS_CONTROL: 'BRIGHTNESS_CONTROL',
  BODY_COLOR_PICKER: 'BODY_COLOR_PICKER',
  QR_SCANNER: 'QR_SCANNER',
};
